### ISSUE TITLE
Code refactoring by SonarLint

### ISSUE THREAD

**Issue by dmitr2ish** [MaiklZak/bookShop#2]
- Install SonarLint plugin
![image](https://user-images.githubusercontent.com/60426238/124447363-b9646a80-dd9a-11eb-83a4-0f6787846458.png)
- Check all classes

**Comment by MaiklZak** [comment]
fixed it

**Comment by dmitr2ish** [comment]
added this in password encoder @SuppressWarnings("squid:S5344")
