### ISSUE TITLE
Refactoring code structure

### ISSUE THREAD

**Issue by dmitr2ish** [MaiklZak/bookShop#3]
Use packages names according the mvc conception.
We will use this packages name
- config - for configuration
- service; 
- repository;
- entity;
- controller - for controller;
   - rest and sub package for rest;
- util - for connectors , tools additional, libs;

security should be place in this packages like a 
- config
  - security
-controllet
  - security
- util
  - security

**Comment by MaiklZak** [comment]
fixed it
